"""add: flag if episode played on public website

Revision ID: 01ff5c5704d2
Revises: 53f90ed694fc
Create Date: 2025-07-24 12:23:26.089313

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01ff5c5704d2'
down_revision: str | Sequence[str] | None = '53f90ed694fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('from_public_website', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'from_public_website')
    # ### end Alembic commands ###
