"""init

Revision ID: 35f09b92a953
Revises: 
Create Date: 2025-07-23 20:37:39.520861

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '35f09b92a953'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('episode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('n_steps', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('INCOMPLETE', 'WON', 'LOST', name='episodestatus'), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_game_id'), 'episode', ['game_id'], unique=False)
    op.create_index(op.f('ix_episode_id'), 'episode', ['id'], unique=False)
    op.create_index(op.f('ix_episode_user_id'), 'episode', ['user_id'], unique=False)
    op.create_table('transition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('obs_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('next_obs_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('terminated', sa.Boolean(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transition_episode_id'), 'transition', ['episode_id'], unique=False)
    op.create_index(op.f('ix_transition_id'), 'transition', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transition_id'), table_name='transition')
    op.drop_index(op.f('ix_transition_episode_id'), table_name='transition')
    op.drop_table('transition')
    op.drop_index(op.f('ix_episode_user_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_game_id'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
