name: Backend Merge

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

permissions:
  contents: "read"
  id-token: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t "europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend:${{ github.sha }}" \
                       -t "europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend:latest" .
          docker push --all-tags "europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend"
        working-directory: ./backend

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: skill-arcade-backend
          image: europe-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend:${{ github.sha }}
          region: europe-west2

      - name: Transform URL for WebSocket
        id: ws_url
        run: |
          URL=${{ steps.deploy.outputs.url }}
          WS_URL="wss://${URL#https://}/ws"
          echo "url=$WS_URL" >> $GITHUB_OUTPUT

      - name: Install Dependencies and Build in Frontend
        run: npm ci && npm run build
        env:
          VITE_WS_URL: ${{ steps.ws_url.outputs.url }}
        working-directory: ./frontend

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SKILL_ARCADE_D2194 }}
          channelId: live
          projectId: skill-arcade-d2194
          entryPoint: ./frontend
