name: Frontend PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend_only: ${{ steps.filter.outputs.frontend == 'true' && steps.filter.outputs.backend == 'false' }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  preview:
    needs: filter
    if: ${{ github.event.action != 'closed' && github.event.pull_request.head.repo.full_name == github.repository && needs.filter.outputs.frontend_only == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies and Build in Frontend
        run: npm ci && npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
        working-directory: ./frontend

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SKILL_ARCADE_D2194 }}
          channelId: preview-pr-${{ github.event.pull_request.number }}
          projectId: skill-arcade-d2194
          entryPoint: ./frontend

  cleanup:
    needs: filter
    if: ${{ github.event.action == 'closed' && github.event.pull_request.head.repo.full_name == github.repository && needs.filter.outputs.frontend_only == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SKILL_ARCADE_D2194 }}
          channelId: preview-pr-${{ github.event.pull_request.number }}
          projectId: skill-arcade-d2194
