name: Frontend Merge

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies and Build in Frontend
        run: npm ci && npm run build
        env:
          VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
        working-directory: ./frontend

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SKILL_ARCADE_D2194 }}
          channelId: live
          projectId: skill-arcade-d2194
          entryPoint: ./frontend
