name: PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  GCP_REGION: europe-west2

permissions:
  contents: "read"
  id-token: "write"
  pull-requests: "write"
  checks: "write"

jobs:
  file_changes:
    runs-on: ubuntu-latest

    outputs:
      backend_changed: ${{ steps.filter.outputs.backend == 'true' }}
      frontend_changed: ${{ steps.filter.outputs.frontend == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ID Changed Files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - "backend/**"
            frontend:
              - "frontend/**"

  deploy:
    runs-on: ubuntu-latest

    needs: file_changes
    if: ${{ github.event.action != 'closed' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Google Cloud SDK Init
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Google Cloud Docker Auth
        if: ${{ github.event.action == 'opened' || needs.file_changes.outputs.backend_changed == 'true' }}
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Google Cloud Artifacts Delete Current
        if: ${{ github.event.action == 'opened' || needs.file_changes.outputs.backend_changed == 'true' }}
        run: |
          IMAGE_NAMES=$(gcloud artifacts docker images list ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend --filter="tags:pr-${{ github.event.pull_request.number }}" --format="get(name)")
          if [ -n "$IMAGE_NAMES" ]; then
            for IMAGE in $IMAGE_NAMES; do
              gcloud artifacts docker images delete \
                "$IMAGE" \
                --quiet
            done
          fi

      - name: Docker Build & Google Cloud Artifacts Push
        if: ${{ github.event.action == 'opened' || needs.file_changes.outputs.backend_changed == 'true' }}
        run: |
          docker build --platform linux/amd64 -t "${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend:pr-${{ github.event.pull_request.number }}" .
          docker push "${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend:pr-${{ github.event.pull_request.number }}"
        working-directory: ./backend

      - name: Google Cloud Run Deploy
        if: ${{ github.event.action == 'opened' || needs.file_changes.outputs.backend_changed == 'true' }}
        run: |
          gcloud run deploy "skill-arcade-backend-pr-${{ github.event.pull_request.number }}" \
          --image="${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend:pr-${{ github.event.pull_request.number }}" \
          --region="${{ env.GCP_REGION }}" \
          --platform=managed \
          --allow-unauthenticated \
          --quiet

      - name: Google Cloud Run Service URL
        id: url
        run: |
          URL=$(gcloud run services describe skill-arcade-backend-pr-${{ github.event.pull_request.number }} --platform managed --region ${{ env.GCP_REGION }} --format 'value(status.url)')
          echo "api_url=$URL" >> $GITHUB_OUTPUT
          WS_URL="wss://${URL#https://}"
          echo "ws_url=$WS_URL" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          npm ci && npm run build
          echo ${{ steps.url.outputs.api_url }}
          echo ${{ steps.url.outputs.ws_url }}
        env:
          VITE_API_URL: ${{ steps.url.outputs.api_url }}
          VITE_WS_URL: ${{ steps.url.outputs.ws_url }}
        working-directory: ./frontend

      - name: Firebase Hosting Deploy
        id: deploy_hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: pr-${{ github.event.pull_request.number }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          entryPoint: ./frontend

  cleanup_backend:
    needs: file_changes
    if: ${{ github.event.action == 'closed' && github.event.pull_request.head.repo.full_name == github.repository && needs.file_changes.outputs.backend_changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Google Cloud SDK Init
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Google Cloud Run Delete
        run: |
          gcloud run services delete skill-arcade-backend-pr-${{ github.event.pull_request.number }} \
            --region=${{ env.GCP_REGION }} \
            --quiet \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Google Cloud Artifacts Delete
        run: |
          gcloud artifacts docker images delete \
            ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/skill-arcade/backend:pr-${{ github.event.pull_request.number }} \
            --delete-tags \
            --quiet

  cleanup_frontend:
    needs: file_changes
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest

    steps:
      - name: Firebase Hosting Delete
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: pr-${{ github.event.pull_request.number }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          expires: 1m
